apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sandbox-go
    system: qotd
  name: sandbox-go
spec:
  replicas: 1
  selector:
    matchLabels:
      system: qotd
  template:
    metadata:
      labels:
        app: sandbox-go
        system: qotd
    spec:
      containers:
      - name: sandbox-go
        image: quay.io/rhdevelopers/sandbox-go:latest
        ports:
          - containerPort: 8080